version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      BOT_TOKEN:
      DATABASE_URL:
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./config:/app/config

volumes:
  db_data:
