version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: goy
      POSTGRES_PASSWORD: goy8800
      POSTGRES_DB: psy_match
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      BOT_TOKEN: "8019886114:AAFTURzkplGBB_Dsoy4RfwVidBmqJ8EQiTM"
      DATABASE_URL: "postgres://goy:goy8800@db:5432/psy_match?sslmode=disable"
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./config:/app/config  # Монтирование локальной папки config в контейнер

volumes:
  db_data:
